# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_info',
            fields=[
                ('travel_num', models.AutoField(primary_key=True, serialize=False)),
                ('railro_type', models.CharField(choices=[('general', 'general'), ('premium', 'premium')], default='general', max_length=10)),
                ('railro_day', models.CharField(choices=[('five', '5'), ('seven', '7')], default='five', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Travel_list', models.CharField(default='', max_length=100, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('end_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='schedule.Location_weight')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=20)),
                ('Loc_per', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='travel_info',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travel_info',
            name='start_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='schedule.Location_weight'),
        ),
    ]
