# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('identifier', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=5)),
                ('Loc_per', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Travel_info',
            fields=[
                ('identifier', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mypage.User_info')),
                ('travel_num', models.FloatField(default=0, primary_key=True)),
                ('railro_type', models.CharField(choices=[('general', 'general'), ('premium', 'premium')], default='general', max_length=10)),
                ('railro_day', models.CharField(choices=[('five', '5'), ('seven', '7')], default='five', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('Travel_list', models.CharField(default='', max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('end_loc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='schedule.Location_weight')),
                ('start_loc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='schedule.Location_weight')),
            ],
        ),
    ]
