# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_info',
            name='identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='mypage.User_info'),
        ),
    ]
