# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location_weight',
            fields=[
                ('loc_key', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('eat', models.FloatField(default=0)),
                ('picture', models.FloatField(default=0)),
                ('activity', models.FloatField(default=0)),
                ('media', models.FloatField(default=0)),
                ('popular', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State_info',
            fields=[
                ('state_key', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station_info',
            fields=[
                ('station_key', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('KTX', models.BooleanField(default=False)),
                ('ITX_C', models.BooleanField(default=False)),
                ('ITX_S', models.BooleanField(default=False)),
                ('S', models.BooleanField(default=False)),
                ('M', models.BooleanField(default=False)),
                ('N', models.BooleanField(default=False)),
                ('Com', models.BooleanField(default=False)),
                ('Tour', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Location_weight')),
            ],
        ),
        migrations.AddField(
            model_name='location_weight',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.State_info'),
        ),
    ]
